#!/bin/sh
# Render the HomeRoute DNS persistence desired-state contract.
# Read-only: does not call systemctl, Docker or iptables.

set -eu

printf '%s\n' 'HOMEROUTE_DNS_DESIRED schema=1'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED mode=render_only'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED timer=awg-adguard-dns.timer'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED service=awg-adguard-dns.service'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED schedule_kind=monotonic'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED on_boot_sec=30'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED on_unit_active_sec=60'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED persistent=true'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED accuracy_sec=10'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED randomized_delay_sec=0'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED helper_path=/usr/local/sbin/awg-adguard-dns.sh'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED target_resolution=docker_inspect_runtime_ipv4'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED network=amnezia-dns-net'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED adguard_container=adguard-home'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED awg_container=amnezia-awg2'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED runtime_ip_logging=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED rule_scope=inside_awg_container'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED table=nat'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED chain=PREROUTING'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED protocols=tcp,udp'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED destination_port=53'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED check_before_insert=true'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED insert_operation=-I'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED broad_flush_allowed=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED container_restart_allowed=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED container_remove_allowed=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED reboot_allowed=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED live_apply=false'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED helper_source_identity=NOT_ADOPTED_PENDING_SCHEMA2_LIVE_CAPTURE'
printf '%s\n' 'HOMEROUTE_DNS_DESIRED result=PASS'
